import type { BlogPost } from "@/types/site";

export const blogPosts: BlogPost[] = [
  {
    slug: "what-we-shipped-in-q1",
    title: "What we shipped in Q1",
    excerpt: "Figma integration, faster timelines, redesigned dashboards, and dozens of improvements. Here's everything that went live.",
    category: "Product Updates",
    author: "Flowline Team",
    date: "Feb 9, 2026",
    readTime: "4 min read",
    image: "/assets/blog-q1.webp",
    cardImage: "/assets/blog-q1-card.avif",
    tabletImage: "/assets/blog-q1-tablet.avif",
    blocks: [
      { heading: "Biggest quarter yet", paragraphs: ["First quarter of 2026 was our biggest shipping quarter yet. Here's a recap of the major features and improvements that went live."] },
      { heading: "Figma integration", paragraphs: ["We launched the Figma integration in early February. You can now link Figma files directly to tasks and preview designs inline without leaving Flowline. Design teams told us they were losing context switching between tools, and this closes that gap. Over 2,000 teams connected Figma within the first two weeks."] },
      { heading: "Faster timeline rendering", paragraphs: ["Projects with 500+ tasks now load up to three times faster, and scrolling and drag-and-drop on the timeline view are noticeably smoother. This was the number one performance request from our larger customers."] },
      { heading: "Redesigned project dashboard", paragraphs: ["The new layout is cleaner, loads faster, and includes a progress ring that shows project completion at a glance. We also added quick-action buttons so you can create tasks, invite members, and access settings without drilling into menus."] },
      { heading: "Bug fixes and smaller improvements", paragraphs: ["Notification preferences were resetting after logout for some users — that's been resolved. We also shipped faster search results, better mobile responsiveness on task detail views, improved CSV export formatting, and updated keyboard shortcuts for power users."] },
      { heading: "What's coming in Q2", paragraphs: ["Custom automation rules for Business plans, workload heatmaps, and a refreshed integrations marketplace. Stay tuned."] },
    ],
  },
  {
    slug: "the-real-cost-of-context-switching",
    title: "The real cost of context switching",
    excerpt: "Five context switches a day costs you over two hours of focus. The fix isn't discipline — it's better systems.",
    category: "Remote Work",
    author: "David Park",
    date: "May 28, 2026",
    readTime: "3 min",
    image: "/assets/blog-context-switching.webp",
    cardImage: "/assets/blog-context-switching-card.avif",
    tabletImage: "/assets/blog-context-switching-tablet.avif",
    blocks: [
      { heading: "The hidden tax on your day", paragraphs: ["Every time you switch between tasks, your brain pays a tax. Research suggests it takes an average of 23 minutes to fully refocus after an interruption. In a typical workday with five or six context switches, that's over two hours lost — not to meetings, not to breaks, just to the mental cost of jumping between things.", "For teams using multiple tools, the problem compounds. Checking tasks in one app, messages in another, files in a third, and updates in a fourth. Each switch feels small, but they add up to a fragmented day where deep work barely happens."] },
      { heading: "Consolidate your tools", paragraphs: ["Every app you eliminate removes a set of daily switches. If your task management, communication, and file sharing can live in one workspace, that's three fewer apps competing for your attention throughout the day."] },
      { heading: "Batch similar work together", paragraphs: ["Instead of responding to messages as they arrive, check them at set intervals — maybe once in the morning, once after lunch, and once before end of day. Instead of reviewing tasks one at a time as notifications pop up, block 20 minutes to review everything at once. Batching turns ten small interruptions into one focused session."] },
      { heading: "Protect deep work time", paragraphs: ["Block two to three hours each day where you close everything except the task you're working on. No Slack, no email, no notifications. Communicate this to your team so they know you're not ignoring them — you're doing the work that actually moves projects forward."] },
      { heading: "Design your notifications intentionally", paragraphs: ["Most people accept default notification settings and then wonder why they're constantly distracted. Turn off everything that isn't urgent or directly relevant to your current work. You can always check updates when you're ready — you don't need them pushed to you in real time.", "Context switching isn't a discipline problem. It's a systems problem. Fix the systems — fewer tools, batched communication, protected focus time, intentional notifications — and the focus follows."] },
    ],
  },
  {
    slug: "workflow-automation-start-with-these-5-rules",
    title: "Workflow automation: start with these 5 rules",
    excerpt: "You don't need a complex system to start automating. These five rules take ten minutes to set up and save hours every week.",
    category: "Productivity",
    author: "James Okoro",
    date: "Feb 10, 2026",
    readTime: "5 min read",
    image: "/assets/blog-automation.webp",
    cardImage: "/assets/blog-automation-card.avif",
    tabletImage: "/assets/blog-automation-tablet.avif",
    blocks: [
      { heading: "Why most teams don't automate", paragraphs: ["Automation is the most underused feature in every project management tool. Teams set up their boards, add their tasks, and then manually do the same repetitive actions every day — moving cards, sending updates, assigning tasks. Over and over.", "You don't need a complex system to start automating. Start with these five rules and you'll save hours every week."] },
      { heading: "Rule 1: Auto-assign new tasks by project", paragraphs: ["Every project has a default owner or team. When a task is created in that project, it should automatically go to the right person. No more tasks sitting unassigned in a backlog because nobody knew who was responsible."] },
      { heading: "Rule 2: Notify the team on status changes", paragraphs: ["When something moves to \"In Review\" or \"Done,\" the relevant people should know immediately. Not through a standup tomorrow morning — right now, in Slack or wherever your team communicates."] },
      { heading: "Rule 3: Send reminders for approaching due dates", paragraphs: ["A task due in 48 hours with no activity should trigger a gentle ping to the assignee. Most overdue tasks aren't forgotten — they're deprioritized until it's too late. An automated reminder fixes that."] },
      { heading: "Rule 4: Move completed tasks automatically", paragraphs: ["When a task is marked done, move it to the \"Completed\" section or archive it. This keeps your active boards clean without anyone manually tidying up."] },
      { heading: "Rule 5: Create recurring tasks for regular work", paragraphs: ["Weekly reports, monthly reviews, sprint planning prep — anything that happens on a schedule should create itself automatically. Set it once and never think about it again.", "These five rules take about ten minutes to set up. They'll save your team hours of repetitive work every week and eliminate the small tasks that clutter your workflow. Start here, and you'll find more automation opportunities everywhere.", "Author Bio: James Okoro — Engineering Team Lead at Flowline. Writes about automation, developer workflows, and team efficiency."] },
    ],
  },
  {
    slug: "how-to-run-a-project-review-that-people-actually-find-useful",
    title: "How to run a project review that people actually find useful",
    excerpt: "If your reviews don't produce visible changes in how the next project runs, they're theater. Here's how to fix that.",
    category: "Leadership",
    author: "Sarah Mitchell",
    date: "May 13, 2026",
    readTime: "5 min read",
    image: "/assets/blog-project-review.webp",
    cardImage: "/assets/blog-project-review-card.avif",
    tabletImage: "/assets/blog-project-review-tablet.webp",
    blocks: [
      { heading: "Why most reviews fail", paragraphs: ["Most project reviews are a waste of time. The team sits in a room, someone reads through a list of what happened, everyone nods, and nothing changes. The next project makes the same mistakes.", "A good review does two things: it identifies what actually caused problems, and it produces specific changes the team commits to."] },
      { heading: "Separate what happened from why", paragraphs: ["Most reviews spend all their time on the what — deliverable X was late, feature Y had bugs, client Z wasn't happy. That's just a recap. Push past it. Ask why deliverable X was late. Was the scope unclear? Was the owner juggling too many projects? Was there a dependency nobody accounted for?"] },
      { heading: "Limit to three wins and three improvements", paragraphs: ["Not ten, not fifteen — three. When you force prioritization, you focus on what actually matters instead of creating a long list nobody reads."] },
      { heading: "Make every improvement actionable", paragraphs: ["For each improvement, assign a specific action to a specific person with a specific deadline. \"We should communicate better\" is not an action. \"David will write a project brief template by Friday and we'll use it for every new project starting next sprint\" is an action."] },
      { heading: "Keep it to 30 minutes", paragraphs: ["If it takes longer, you're going too broad. A focused review that produces three real changes beats a two-hour session that produces a document nobody opens again.", "The point of a review isn't to document the past. It's to change the future. If your reviews don't produce visible changes in how the next project runs, they're theater."] },
    ],
  },
  {
    slug: "the-async-first-playbook-for-distributed-teams",
    title: "The async-first playbook for distributed teams",
    excerpt: "Distributed teams fail when they try to work like office teams with webcams. Going async-first changes everything.",
    category: "Remote Work",
    author: "David Park",
    date: "May 17, 2026",
    readTime: "7 min read",
    image: "/assets/blog-async.webp",
    cardImage: "/assets/blog-async-card.avif",
    tabletImage: "/assets/blog-async-tablet.webp",
    blocks: [
      { heading: "Why distributed teams struggle", paragraphs: ["Distributed teams fail when they try to work like office teams with webcams. The meetings multiply, the Slack messages pile up, and everyone ends the day feeling busy but behind.", "The fix is going async-first. That doesn't mean no meetings — it means meetings are the exception, not the default."] },
      { heading: "Write everything down", paragraphs: ["Every decision, every project update, every piece of context that someone might need later. If it happened in a call, summarize it in a task comment within five minutes. If it's not written down, it didn't happen."] },
      { heading: "Replace meetings with async updates", paragraphs: ["A daily async check-in where each person writes three lines: what they finished yesterday, what they're working on today, and what's blocking them. It takes two minutes to write and one minute to read. That's three minutes versus a 30-minute standup."] },
      { heading: "Set communication expectations", paragraphs: ["Not everything needs an instant response. Define what goes where: tasks and project updates live in your project management tool, urgent issues go to Slack, and email is for external communication only. When people know where to look, they stop interrupting each other."] },
      { heading: "Build overlap hours intentionally", paragraphs: ["If your team spans time zones, protect a two-hour window where everyone is available for real-time collaboration. Use that window for actual collaboration — pairing, problem-solving, decisions that need a live conversation. Everything else happens async.", "The goal isn't to eliminate real-time communication. It's to make sure real-time is a choice, not a requirement. When you get this right, your distributed team won't just keep up with co-located teams — they'll outperform them."] },
    ],
  },
  {
    slug: "why-your-team-keeps-missing-deadlines",
    title: "Why your team keeps missing deadlines",
    excerpt: "Most teams don't lack talent or effort — they lack visibility. Here's how to fix the system, not the people.",
    category: "Productivity",
    author: "Sarah Mitchell",
    date: "May 5, 2026",
    readTime: "6 min read",
    image: "/assets/blog-deadlines.webp",
    cardImage: "/assets/blog-deadlines-card.avif",
    tabletImage: "/assets/blog-deadlines-tablet.webp",
    blocks: [
      { heading: "The real problem isn't effort", paragraphs: ["Missing a deadline once is a hiccup. Missing them repeatedly is a system problem. And the frustrating part is that most teams don't lack talent or effort — they lack visibility.", "When work lives in scattered tools, priorities get buried and no one has a reliable picture of what's due when. People work hard on the wrong things. Deadlines pass because someone assumed someone else was handling it.", "The fix isn't working harder. It's making work visible."] },
      { heading: "Make work visible", paragraphs: ["Start with a single source of truth for every project. Every task should have an owner, a due date, and a status that the whole team can see. This sounds obvious, but most teams don't actually do it consistently."] },
      { heading: "Build a weekly rhythm", paragraphs: ["A 15-minute check-in where the team reviews what's due this week, what's blocked, and what's at risk. Not a status meeting — a prioritization meeting. The goal isn't updates. It's alignment."] },
      { heading: "Spot conflicts before they happen", paragraphs: ["Use timeline views to catch scheduling problems early. If two major deliverables are due the same week and assigned to the same person, you'll see it a week early instead of the day it's due.", "Deadlines aren't the problem. Lack of visibility is. Fix that, and your team will start hitting dates they used to miss."] },
    ],
  },
];

export function getBlogPost(slug: string) {
  return blogPosts.find((post) => post.slug === slug);
}
