export const privacySections = [
  { heading: "Who We Are", paragraphs: ["Flowline is a project management platform built for teams. For the purposes of data protection law, Flowline is the data controller of your personal information. You can contact us at hello@flowline.com."] },
  { heading: "What Data We Collect", paragraphs: ["We may collect the following types of personal information:"], bullets: ["Contact information — your name, email address, and company name when you submit a form on our website", "Correspondence — any messages or enquiries you send to us", "Usage data — information about how you interact with our website, including pages visited and time spent on site", "Marketing preferences — whether you have opted in to receive updates from us"] },
  { heading: "How We Use Your Data", paragraphs: ["We use your personal information to:"], bullets: ["Respond to your enquiries and provide access to our platform", "Send you product updates and insights, where you have opted in", "Improve our website and understand how it is used", "Comply with our legal and regulatory obligations"] },
  { heading: "Legal Basis for Processing", paragraphs: ["We process your personal data on the following grounds:"], bullets: ["Legitimate interests — to respond to enquiries and manage our relationship with you", "Consent — where you have opted in to receive marketing communications", "Legal obligation — where we are required to process your data by law"] },
  { heading: "How Long We Keep Your Data", paragraphs: ["We retain your personal data for as long as necessary to fulfil the purposes for which it was collected, or as required by law. Marketing data is retained until you unsubscribe or withdraw your consent."] },
  { heading: "Sharing Your Data", paragraphs: ["We do not sell your personal data. We may share your data with trusted third-party service providers who assist us in operating our platform — for example, email and analytics providers. These parties are bound by contractual obligations to keep your data secure."] },
  { heading: "Your Rights", paragraphs: ["Under applicable data protection law, you have the right to:"], bullets: ["Access the personal data we hold about you", "Request correction of inaccurate data", "Request deletion of your data", "Withdraw your consent to marketing at any time", "Lodge a complaint with the relevant data protection authority"], trailing: "To exercise any of these rights, please contact us at hello@flowline.com." },
  { heading: "Cookies", paragraphs: ["We use cookies to improve your experience on our website. For more information, please see our Cookie Policy."] },
  { heading: "Changes to This Policy", paragraphs: ["We may update this Privacy Policy from time to time. Any changes will be posted on this page with an updated date."] },
  { heading: "Contact", paragraphs: ["If you have any questions about this policy or how we handle your data, please contact us at hello@flowline.com."] },
];

export const termsSections = [
  { heading: "Use of the Platform", paragraphs: ["Flowline is a project management platform designed for teams and organizations. You agree to use the platform only for lawful purposes and in accordance with these terms. You must not:"], bullets: ["Use the platform in any way that violates applicable laws or regulations", "Attempt to gain unauthorised access to any part of the platform", "Use the platform to generate harmful, misleading, or illegal content", "Resell or redistribute access to the platform without our written consent"] },
  { heading: "Account Responsibility", paragraphs: ["You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately at hello@flowline.com if you suspect any unauthorised use of your account."] },
  { heading: "Intellectual Property", paragraphs: ["All content, design, and technology on the Flowline platform is owned by or licensed to Flowline. You may not copy, reproduce, or distribute any part of the platform without our prior written permission. Content you create using Flowline — including tasks, projects, files, and comments — remains yours. We do not claim ownership over your data or outputs."] },
  { heading: "Subscriptions and Payments", paragraphs: ["Flowline offers multiple paid plans. By subscribing to a paid plan, you agree to pay the applicable fees. Fees are billed in advance on a monthly or annual basis depending on your selected billing cycle. Fees are non-refundable except where required by law. We reserve the right to change our pricing at any time, with reasonable notice provided to existing subscribers."] },
  { heading: "Free Trial", paragraphs: ["Flowline offers a 14-day free trial on all paid plans. No credit card is required to start a trial. At the end of the trial period, your account will be downgraded unless you subscribe to a paid plan. Any data created during the trial will be retained for 30 days after the trial ends."] },
  { heading: "Cancellation", paragraphs: ["You may cancel your subscription at any time. Cancellation will take effect at the end of your current billing period. You will retain access to paid features until that date. After cancellation, your data will be retained for 30 days before being permanently deleted."] },
  { heading: "Limitation of Liability", paragraphs: ["To the fullest extent permitted by law, Flowline shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform. Our total liability to you shall not exceed the amount you paid to us in the twelve months preceding the claim."] },
  { heading: "Disclaimer of Warranties", paragraphs: ["Flowline is provided on an \"as is\" and \"as available\" basis. We do not guarantee that the platform will be error-free, uninterrupted, or meet your specific requirements."] },
  { heading: "Changes to These Terms", paragraphs: ["We may update these Terms of Use from time to time. Any changes will be posted on this page with an updated date. Continued use of the platform after changes are posted constitutes your acceptance of the revised terms."] },
  { heading: "Governing Law", paragraphs: ["These terms are governed by and construed in accordance with applicable law. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the relevant courts."] },
  { heading: "Contact", paragraphs: ["If you have any questions about these terms, please contact us at hello@flowline.com."] },
];
